# Generated by Django 6.1 on 2026-08-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPotencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.CharField(max_length=100, unique=True, verbose_name='Potência')),
                ('meta_quantidade', models.PositiveIntegerField(default=0, verbose_name='Meta (Quantidade)')),
            ],
            options={
                'verbose_name': 'Meta por Potência',
                'verbose_name_plural': 'Metas por Potência',
            },
        ),
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valido', models.BooleanField(default=True, help_text='Desmarque se for um teste', verbose_name='Inscrição Válida?')),
                ('data_hora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data da Inscrição')),
                ('nome_jogador1', models.CharField(max_length=200, verbose_name='Nome Jogador 1')),
                ('potencia_jogador1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Potência Jogador 1')),
                ('loja_jogador1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Loja Jogador 1')),
                ('nome_jogador2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Jogador 2')),
                ('potencia_jogador2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Potência Jogador 2')),
                ('loja_jogador2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Loja Jogador 2')),
                ('status_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=50, verbose_name='Status do Pagamento')),
            ],
            options={
                'verbose_name': 'Dupla',
                'verbose_name_plural': 'Duplas',
                'unique_together': {('nome_jogador1', 'nome_jogador2', 'data_hora')},
            },
        ),
    ]
