# Generated by Django 6.1 on 2026-08-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='purgado',
            field=models.BooleanField(default=False, help_text='Marcado quando o usuário deleta a inscrição na UI', verbose_name='Registro Purgado?'),
        ),
    ]
