# Generated by Django 6.1 on 2026-08-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dupla_purgado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='origem',
            field=models.CharField(choices=[('Eletrônico', 'Eletrônico (Google Forms)'), ('Manual', 'Ficha Manual (Física)')], default='Eletrônico', max_length=50, verbose_name='Origem da Inscrição'),
        ),
    ]
