# Generated by Django 6.1 on 2026-08-10 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dupla_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, unique=True, verbose_name='Nome Completo')),
                ('sigla', models.CharField(max_length=50, unique=True, verbose_name='Sigla')),
                ('meta_inscricoes', models.PositiveIntegerField(default=0, verbose_name='Meta de Inscrições')),
            ],
            options={
                'verbose_name': 'Potência',
                'verbose_name_plural': 'Potências',
            },
        ),
        migrations.DeleteModel(
            name='MetaPotencia',
        ),
        migrations.AlterField(
            model_name='dupla',
            name='potencia_jogador1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Potência Jogador 1 (Legado)'),
        ),
        migrations.AlterField(
            model_name='dupla',
            name='potencia_jogador2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Potência Jogador 2 (Legado)'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='potencia_obj1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores1', to='dashboard.potencia'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='potencia_obj2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores2', to='dashboard.potencia'),
        ),
    ]
