# Generated by Django 6.1 on 2026-08-10 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_potencia_delete_metapotencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dupla',
            name='potencia_jogador1',
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='potencia_jogador2',
        ),
        migrations.RenameField(
            model_name='dupla',
            old_name='potencia_obj1',
            new_name='potencia_jogador1',
        ),
        migrations.RenameField(
            model_name='dupla',
            old_name='potencia_obj2',
            new_name='potencia_jogador2',
        ),
    ]
