# Generated by Django 6.1 on 2026-08-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_dupla_potencia_obj1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número da Mesa')),
                ('ocupada', models.BooleanField(default=False, verbose_name='Ocupada?')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.PositiveIntegerField(verbose_name='Posição na Fila')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Entrada')),
                ('dupla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fila', to='dashboard.dupla')),
            ],
            options={
                'verbose_name': 'Fila de Espera',
                'verbose_name_plural': 'Fila de Espera',
                'ordering': ['posicao', 'data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vitoria', models.CharField(blank=True, choices=[('Simples', 'Vitória Simples (3 pts)'), ('Capote', 'Capote (4 pts)'), ('Rolha', 'Rolha (5 pts)'), ('Lisa', 'Lisa (6 pts)')], max_length=20, null=True, verbose_name='Tipo de Vitória')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('dupla_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_a', to='dashboard.dupla')),
                ('dupla_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_como_b', to='dashboard.dupla')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='dashboard.mesa')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='dashboard.dupla')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
