# Generated by Django 6.1 on 2026-08-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_mesa_filaespera_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='acompanhantes_adultos',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos Acompanhantes'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='acompanhantes_criancas',
            field=models.PositiveIntegerField(default=0, verbose_name='Crianças Acompanhantes'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='apelido_jogador1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido J1'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='apelido_jogador2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido J2'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='email_jogador1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail J1'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='email_jogador2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail J2'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='idade_jogador1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade J1'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='idade_jogador2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade J2'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='profissao_jogador1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissão J1'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='profissao_jogador2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Profissão J2'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='telefone_jogador1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone J1'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='telefone_jogador2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone J2'),
        ),
    ]
