# Generated by Django 6.1 on 2026-08-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dupla_acompanhantes_adultos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='cim_jogador1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CIM J1'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='cim_jogador2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CIM J2'),
        ),
        migrations.AlterField(
            model_name='dupla',
            name='nome_jogador1',
            field=models.CharField(max_length=200, verbose_name='Nome J1'),
        ),
    ]
