# Generated by Django 6.1 on 2026-08-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_dupla_cim_jogador1_dupla_cim_jogador2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
    ]
