# Generated by Django 6.1 on 2026-08-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dupla_comprovante_dupla_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='banco_comprovante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Banco do Pagador'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='documento_comprovante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nº do Documento (ID Bancário)'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='pagador_comprovante',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome do Pagador (Comprovante)'),
        ),
    ]
