# Generated by Django 6.1 on 2026-08-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_dupla_metadados_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dupla',
            name='valido',
            field=models.BooleanField(default=False, help_text='Marque após conferir os dados e o pagamento', verbose_name='Inscrição Válida?'),
        ),
    ]
