# Generated by Django 6.1 on 2026-08-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_dupla_valido'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='ficha_inscricao',
            field=models.FileField(blank=True, null=True, upload_to='inscricoes/', verbose_name='Ficha de Inscrição'),
        ),
    ]
