# Generated by Django 6.1 on 2026-08-17 19:37

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_dupla_ficha_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=dashboard.models.upload_comprovante_path, verbose_name='Arquivo do Comprovante')),
                ('pagador', models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome do Pagador')),
                ('banco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Banco')),
                ('identificador', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID da Transação')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora do Pagamento')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=dashboard.models.upload_ficha_path, verbose_name='Ficha Digitalizada')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='banco_comprovante',
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='documento_comprovante',
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='pagador_comprovante',
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='comprovante',
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='ficha_inscricao',
        ),
        migrations.AddField(
            model_name='dupla',
            name='comprovante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dupla', to='dashboard.comprovante'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='ficha_inscricao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dupla', to='dashboard.fichainscricao'),
        ),
    ]
