# Generated by Django 6.1 on 2026-08-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_dupla_valido_dupla_status_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Declarado'),
        ),
    ]
