# Generated by Django 6.1 on 2026-08-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_comprovante_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dupla',
            name='acompanhantes_adultos',
        ),
        migrations.RemoveField(
            model_name='dupla',
            name='acompanhantes_criancas',
        ),
        migrations.AddField(
            model_name='dupla',
            name='acompanhantes_j1_adultos',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos J1'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='acompanhantes_j1_criancas',
            field=models.PositiveIntegerField(default=0, verbose_name='Crianças J1'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='acompanhantes_j2_adultos',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos J2'),
        ),
        migrations.AddField(
            model_name='dupla',
            name='acompanhantes_j2_criancas',
            field=models.PositiveIntegerField(default=0, verbose_name='Crianças J2'),
        ),
    ]
