# Generated by Django 6.1 on 2026-08-21 14:38

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_dupla_acompanhantes_adultos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='tipo',
            field=models.CharField(choices=[('BANCARIO', 'Comprovante Bancário'), ('RECIBO', 'Recibo Sistêmico')], default='BANCARIO', max_length=20, verbose_name='Tipo de Registro'),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=dashboard.models.upload_comprovante_path, verbose_name='Arquivo do Comprovante'),
        ),
    ]
