# Generated by Django 6.1 on 2026-08-22 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_comprovante_tipo_alter_comprovante_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='ocupada',
        ),
        migrations.AddField(
            model_name='mesa',
            name='dupla_rei',
            field=models.ForeignKey(blank=True, help_text='Dupla que venceu e permanece na mesa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_como_rei', to='dashboard.dupla'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('desativada', 'Desativada'), ('livre', 'Livre'), ('em_disputa', 'Em Disputa')], default='desativada', max_length=20, verbose_name='Status da Mesa'),
        ),
        migrations.CreateModel(
            name='Confronto',
            fields=[
                ('numero_sequencial', models.AutoField(primary_key=True, serialize=False, verbose_name='Número Sequencial')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='em_andamento', max_length=20, verbose_name='Status do Confronto')),
                ('pontos_d1', models.PositiveIntegerField(default=0, verbose_name='Pontos Dupla 1')),
                ('pontos_d2', models.PositiveIntegerField(default=0, verbose_name='Pontos Dupla 2')),
                ('tipo_vitoria', models.CharField(blank=True, choices=[('Simples', 'Vitória Simples (3 pts)'), ('Capote', 'Capote (4 pts)'), ('Rolha', 'Rolha (5 pts)'), ('Lisa', 'Lisa (6 pts)')], max_length=20, null=True, verbose_name='Tipo de Vitória')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('dupla_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confrontos_como_d1', to='dashboard.dupla')),
                ('dupla_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confrontos_como_d2', to='dashboard.dupla')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrontos', to='dashboard.mesa')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitorias', to='dashboard.dupla')),
            ],
            options={
                'verbose_name': 'Confronto',
                'verbose_name_plural': 'Confrontos',
            },
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
    ]
