# Generated by Django 6.1 on 2026-08-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_comprovante_tipo_alter_comprovante_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Árbitro',
                'verbose_name_plural': 'Árbitros',
            },
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='ocupada',
        ),
        migrations.AddField(
            model_name='mesa',
            name='arbitro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='dashboard.arbitro'),
        ),
        migrations.CreateModel(
            name='Confronto',
            fields=[
                ('numero_jogo', models.AutoField(primary_key=True, serialize=False, verbose_name='Número do Jogo')),
                ('pontos_a', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pontos Dupla A')),
                ('pontos_b', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pontos Dupla B')),
                ('status', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Finalizado', 'Finalizado')], default='Em Andamento', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('dupla_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confrontos_como_a', to='dashboard.dupla')),
                ('dupla_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confrontos_como_b', to='dashboard.dupla')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confrontos', to='dashboard.mesa')),
            ],
            options={
                'verbose_name': 'Confronto',
                'verbose_name_plural': 'Confrontos',
            },
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
    ]
