# Generated by Django 6.1 on 2026-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_arbitro_remove_mesa_ocupada_mesa_arbitro_confronto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='credenciamento',
            field=models.IntegerField(blank=True, help_text='Número físico dado à dupla na entrada do evento', null=True, verbose_name='Nº Credenciamento'),
        ),
    ]
