# Generated by Django 6.1 on 2026-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_dupla_credenciamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='confronto',
            name='gato_a',
            field=models.BooleanField(default=False, verbose_name='Infração Gato (A)'),
        ),
        migrations.AddField(
            model_name='confronto',
            name='gato_b',
            field=models.BooleanField(default=False, verbose_name='Infração Gato (B)'),
        ),
        migrations.AlterField(
            model_name='confronto',
            name='pontos_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pontos B'),
        ),
    ]
